### ISSUE TITLE
Maybe compare with few other packages too?

### ISSUE THREAD

**Issue by kaushalmodi** [alezost/dim.el#2]
Hi,

Thanks for developing this package.

I use [`rich-minority`](https://github.com/Malabarba/rich-minority) along with [`smart-mode-line`](https://github.com/Malabarba/smart-mode-line) to take care of abbreviating/hiding the minor mode lighter names.

I have heard of the [`cyphejor`](https://github.com/mrkkrp/cyphejor) package via [this Emacs.SE post](http://emacs.stackexchange.com/a/16599/115) which does the job of abbreviating the major mode names automatically/manually.

How would you compare this package with `rich-minority` and `cyphejor`?

Also feel free to add an answer to [that Emacs.SE question](http://emacs.stackexchange.com/q/16545/115) suggesting the use of this package as it seems fit.

**Comment by alezost** [comment]
Hello, thanks for the pointers, I didn't know about these packages.  I
have updated README (https://github.com/alezost/dim.el#why) to mention
them.

As for the stackexchange question, I don't think `dim` should be
mentioned there.  The author wanted to have some automation, and when he
didn't find a package for his needs, he wrote one (cyphejor).  `dim`
doesn't provide an automatic abbreviation, it is for manual setting of
mode-line names.

**Comment by kaushalmodi** [comment]
Thanks for updating the documentation and your reply.
