### ISSUE TITLE
Dim not hiding org-indent-mode when loading Org files

### ISSUE THREAD

**Issue by sondr3** [alezost/dim.el#5]
I wanted to try out Dim to compare it to Delight which I've been using previously, and I really quote like the syntax for it. I am however having a problem, I have my configuration in a org file that I tangle to a `init.el`. In text files I have `auto-fill-mode` automatically activate and in Org files `org-indent-mode` activate. Dim successfully changes the name of `auto-fill-mode` to " F" when opening a Org file, and I want to hide `org-indent-mode` too but it doesn't hide it when loading into org-mode files. Manually running C-x C-e on `  (dim-minor-name 'org-indent-mode "")` hides it, but not when opening the file. Any ideas? Delight does this correct.

**Comment by alezost** [comment]
Hm, I can't reproduce.  How do you activate `org-indent-mode` in files, with ``#+STARTUP: indent`` or something else?

Also how do you make dim to hide this indicator in your `init.el`?
Simply with:

```elisp
(dim-minor-name 'org-indent-mode "")
```

If so, most likely, it's not enough: if org-mode is not loaded when
`dim-minor-name` is called then there is nothing to change yet.  You'll
probably have "Unknown minor mode ’org-indent-mode’." message in
`*Messages*` buffer.  If you have, try the following line instead:

```elisp
(dim-minor-name 'org-indent-mode "" 'org-indent)
```

**Comment by sondr3** [comment]
Thanks, that worked! I declared `org-indent-mode` with `(setq org-startup-indented t)`, so it starts up every Org file indented. But it works now, thanks a bunch!
