### ISSUE TITLE
README.org broken link: delight

### ISSUE THREAD

**Issue by duianto** [alezost/dim.el#9]
In the About section: https://github.com/alezost/dim.el#about
In the second sentence:
>This is an alternative to delight package (see Why? section below).

### The text: `delight` links to:
http://www.emacswiki.org/emacs/delight.el
It leads to an emacswiki page that says:
>delight.el
This page does not exist, but you can create it now.

I'm not sure what the url should point to.
This seems to be the repositories source:
http://git.savannah.gnu.org/cgit/delight.git/

But in this dim.el repositories, README.org, Why? section, there is a link with the text `delight` that leads to:
http://www.emacswiki.org/emacs/DelightedModes

The other readme.org links work, except for the already reported `Why?` link.
Fix why? link in README #1

**Comment by alezost** [comment]
Hello, and sorry for the delay :blush:

I have fixed that link to point to https://elpa.gnu.org/packages/delight.html

Thank you!
